version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/cleanerapp
    command: ["sh", "start.sh"]
    ports:
      - 8025:8000
    image: cleanerapp:django
    container_name: cleanerapp_container
    # command: python manage.py runserver 0.0.0.0:8000