version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/cleanerapp
    ports:
      - 8081:8000
    image: cleanerapp:django
    container_name: cleanerapp_container
    # command: python manage.py runserver 0.0.0.0:8000