# Generated by Django 4.2.5 on 2023-09-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleanerapp", "0003_alter_cleaner_user_alter_staff_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksdata",
            name="comment",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
