# Generated by Django 4.2.5 on 2023-09-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleanerapp", "0004_worksdata_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksdata",
            name="examiner",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
