# Generated by Django 4.2.5 on 2023-09-26 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cleanerapp", "0005_worksdata_examiner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worksdata",
            old_name="examiner",
            new_name="staff",
        ),
    ]
