# Generated by Django 4.2.5 on 2023-09-26 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cleanerapp", "0006_rename_examiner_worksdata_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="worksdata",
            name="staff",
        ),
        migrations.AddField(
            model_name="worksdata",
            name="checker",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cleanerapp.checker",
            ),
        ),
    ]
