# Generated by Django 4.2.5 on 2023-09-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cleanerapp", "0009_alter_worksdata_checker"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worksdata",
            old_name="checker",
            new_name="staff",
        ),
    ]
