# Generated by Django 4.2.5 on 2023-09-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleanerapp", "0010_rename_checker_worksdata_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="alqur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ayah", models.CharField(max_length=500)),
                ("mean", models.CharField(max_length=500)),
                ("read", models.CharField(max_length=500)),
            ],
        ),
    ]
