# Generated by Django 5.0.2 on 2024-03-07 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanerapp', '0012_delete_alqur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name_plural': 'ตึก'},
        ),
        migrations.AlterModelOptions(
            name='checker',
            options={'verbose_name_plural': 'พนักงานเช็คความสะอาด'},
        ),
        migrations.AlterModelOptions(
            name='cleaner',
            options={'verbose_name_plural': 'พนักงานทำความสะอาด'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'ห้อง'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'แอดมิน'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': 'งาน'},
        ),
        migrations.AlterModelOptions(
            name='worksdata',
            options={'verbose_name_plural': 'บันทึกข้อมูลทำความสะอาด'},
        ),
    ]
